#!/usr/bin/env bash
#it parses Apache log files in list format.
# it groups visitors by IP and HTTP status code.
#it displays the number of occurrences, IP, and HTTP status
#it is the code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
