#!/bin/bash

# Define variables
KEY_NAME="school"
KEY_BITS="4096"
PASSPHRASE="betty"

#it will  Generate RSA key pair with passphrase
ssh-keygen -t rsa -b "$KEY_BITS" -f "$KEY_NAME" -N "$PASSPHRASE"

#it will  Provide feedback
echo "RSA key pair created:"
echo "Private key: $KEY_NAME"
echo "Public key: ${KEY_NAME}.pub"

